### ISSUE TITLE
limited restaurants

### ISSUE THREAD

**Issue by suprajaboga** [Its-Anth0ny/YumXpress#1]
I'm getting only 8 restaurants in the home page, in your home page there are around 20 restaurants. How to achieve that?

**Comment by Its-Anth0ny** [comment]
![image](https://github.com/Its-Anth0ny/YumXpress/assets/81018055/fc727171-c339-4d34-834d-66d3b457e9a3)

there are many cards. I am getting data from cards[1] (id = "top_brands_for_you"). It has 20 restaurants.
